name: Deploy to VPS (Build on VPS with Git Pull)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy and build on VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}          
          script: |
            cd ~/firephenix-website
            # Ensure we have the latest changes
            git fetch origin main
            git reset --hard origin/main
                  
            # Build with verbose output
            npm run build
            
            # Copy built files to web root (adjust path as needed)
            rm -rf /var/www/firephenix-website/*
            cp -r dist/* /var/www/firephenix-website/
            
            # Reload web server (adjust for your setup)
            sudo systemctl reload nginx
